name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
          working_directory: cv_eng
          latexmk_use_xelatex: true

      - name: Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          tag_name: 1.0.0

      - name: Upload CV
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: cv_eng/resume.pdf
          asset_name: RomanDugaev_CV.pdf
          asset_content_type: application/pdf
          
