name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: RomanDugaev_CV.tex
          working_directory: cv_eng
          latexmk_use_xelatex: true
          
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: RomanDugaev_CV
          path: cv_eng/RomanDugaev_CV.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 1.0.0
